name: Move Pull Request Required Card
on:
  issues:
    types: [opened]
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Goods For You
          column: In Review
          repo-token: ${{ secrets.GOODSFORYOU_TOKEN }}
